name: "Hosted: Network Filtering with Harden-Runner"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: crazy-max/ghaction-github-status@v4

      - uses: actions/checkout@v3

      - name: listen.dev Scan
        uses: listendev/action@v0.8.0
        with:
          ci: true
          jwt: ${{ secrets.LSTN_JWT }}


      - name: npm install
        run: |
          cd ./src/exfiltration-demo
          npm install

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: src/exfiltration-demo

      - uses: madhead/semver-utils@latest
        id: version
        with:
          version: 1.2.3

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ github.repository }}/prod:latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          workdir: ./src/exfiltration-demo
