name: Unexpected Outbound Calls
on:
  workflow_dispatch:
jobs:
  unexpected-outbound-calls:
    name: UnexpectedOutboundCalls
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: listen.dev Scan
        uses: listendev/action@v0.8.0
        with:
          ci: true
          jwt: ${{ secrets.LSTN_JWT }}

      
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - run: "curl https://attacker.com -L  || true"
      - run: "curl https://google.com -L  || true"
      - run: "curl microsoft.com:443  --connect-timeout 5 || true"
      - run: "curl amazon.com:443  --connect-timeout 5 || true"
